name: "Mark Discussion Comment Answer ✅"
description: "Create random unicode text from an input range"
author: "Wesley Scholl"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  GITHUB_TOKEN:
    description: "GitHub personal access token."
    required: true

branding:
  icon: "check-circle"
  color: "green"
