name: "Mark Discussion Comment Answer ✅"
description: "Mark discussion comments as answers based on reaction threshold."
author: "Wesley Scholl"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  GH_TOKEN:
    description: "The GitHub token for authentication."
    required: false
    default: "${{ secrets.GITHUB_TOKEN }}"

branding:
  icon: "check-circle"
  color: "green"
