name: "Mark Discussion Comment Answer ✅"
description: "Create random unicode text from an input range"
author: "Wesley Scholl"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  COMMENT_ID:
    description: "Comment ID to be marked as the answer."
    required: true
  GITHUB_TOKEN:
    description: "GitHub personal access token."
    required: false
    default: "${{ github.token }}"

branding:
  icon: "check-circle"
  color: "green"
