name: Mark Discussion Comment Answer

on:
  discussion_comment:
    types: [created]

jobs:
  mark-comment-answer:
    name: Mark a discussion comment as the answer
    if: |
      toJSON(github.event.locked) == null && 
      toJSON(github.event.discussion.category.is_answerable) == true &&
      toJSON(github.event.discussion.answer_chosen_at) == null
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Run Mark Discussion Comment Answer
        id: markanswer
        uses: ./
        with:
          GH_TOKEN: "${{ secrets.DISCUSS_TOKEN }}"
          reaction_threshold: 3
          comment_threshold: 3
          
      - name: Show Mark Answer Output
        run: |
          echo "discussionId = ${{ steps.markanswer.outputs.discussionId }}"
          echo "clientMutationId = ${{ steps.markanswer.outputs.clientMutationId }}"
          echo "commentText = ${{ steps.markanswer.outputs.commentText }}"
          echo "reactionThreshold = ${{ steps.markanswer.outputs.reactionThreshold }}"
          echo "totalReactions = ${{ steps.markanswer.outputs.totalReactions }}"
          echo "commentId = ${{ steps.markanswer.outputs.commentId }}"
