name: Mark Discussion Comment Answer

on:
  discussion_comment:
    types: [created]

jobs:
  mark-comment-answer:
    name: Mark a discussion comment as the answer
    if: true == true
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          ANSWERABLE: ${{ toJSON(github.event.discussion.category.is_answerable) }}
          COMMENTS: ${{ toJSON(github.event.discussion.comments) }}
          ANSWER: ${{ toJSON(github.event.discussion.answer_chosen_at) }}
          LOCKED: ${{ toJSON(github.event.locked) }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$ANSWERABLE"
          echo ${{ ANSWERABLE == true }}
          echo "$COMMENTS"
          echo ${{ ANSWER == null }}
          echo ${{ LOCKED == null }}
          echo "$GITHUB_CONTEXT"
  
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Run Mark Discussion Comment Answer
        id: markanswer
        uses: ./
        with:
          GH_TOKEN: "${{ secrets.DISCUSS_TOKEN }}"
          reaction_threshold: 3
          comment_threshold: 3
          
      - name: Show Mark Answer Output
        run: |
          echo "discussionId = ${{ steps.markanswer.outputs.discussionId }}"
          echo "clientMutationId = ${{ steps.markanswer.outputs.clientMutationId }}"
          echo "commentText = ${{ steps.markanswer.outputs.commentText }}"
          echo "reactionThreshold = ${{ steps.markanswer.outputs.reactionThreshold }}"
          echo "totalReactions = ${{ steps.markanswer.outputs.totalReactions }}"
          echo "commentId = ${{ steps.markanswer.outputs.commentId }}"
